# This is a basic workflow to help you get started with Actions

name: Generate Stats Images

# Controls when the action will run. Triggers the workflow on push events
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'

    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    # Generate all statistics images
    - name: Generate stats images
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true

    - name: Generate snk images
      uses: Platane/snk@v2
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          generated/github-snake.svg
          generated/github-snake-dark.svg?palette=github-dark

    # Import GPG key
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5.1.0
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    # Commits all changed files to the repository
    - name: Commit to the repo
      run: |
        git config --global user.name "Samarium"
        git config --global user.email "28302241+samarium150@users.noreply.github.com"
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -S -m 'chore: update generated files' || echo
        git switch -c generated

    - name: Push to the repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'generated'
        force: true

    # Sync to Gitee mirror
    - name: Sync to Gitee
      run: |
        mirror=https://Samarium:${{ secrets.PASSPHRASE }}@gitee.com/Samarium/github-stats-generator.git
        git remote add mirror "${mirror}"
        git push -f mirror "refs/remotes/origin/*:refs/heads/*"
